// Licensed to Elasticsearch B.V. under one or more contributor
// license agreements. See the NOTICE file distributed with
// this work for additional information regarding copyright
// ownership. Elasticsearch B.V. licenses this file to you under
// the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

// Code generated by beats/dev-tools/cmd/asset/asset.go - DO NOT EDIT.

package include

import (
	"github.com/elastic/beats/libbeat/asset"
)

func init() {
	if err := asset.SetFields("monbeat", "fields.yml", Asset); err != nil {
		panic(err)
	}
}

// Asset returns asset data
func Asset() string {
	return "eJy0WFtvGzcTfdevGOTp+wBp0diNUeihqGsbjdA4MRr7WRmRo13Wu+SG5FpWf33By968q4tjNQ+BeTvnkJw5Q+1kBo+0ncOK0E4ArLA5zeH30OJkmBalFUrO4dcJAMCVkhaFNMBUUSjp18FaUM4N4BOKHFc5gZCAeQ70RNKC3ZZkkgnEafOJB5qBxIICceL+9L2jnO7ffUZ+Aag12Iy8QjAkuZCp78hVCgUZgymZBBadWX6ZMA2UIesEunGm5FqklUZHB2uR09T1u0G08IR55VZCZYh7TGFdUyrbBfNLIFPGRqY4/155qp6OqRvzXd9c81uDo/yOd+tKhodWMx4+uEYbGtBkKy2Jw2rrqVRJjkamYLbGUgFKwiYTLGuFd85OV1IKmY6osaKgf5Q8Qk09879U80TaCCUPi4kT67Dy4ewvPyXppBAHmwkTQjnph+6739xWjMWifBdBXazPgaOtz0HT90po4nOwuqo710oXaHvz6BmL0qXeZZVWxsLZhc3g7Kf3F1N4fzY//zD/cJ6cn58dd7peEmxCIFNMQ5cgmpjSHDZo2v292JTF1OxnudQrYTXqrZ8bTouhswIf7yXpcFEouW9YjdIgs+19hHN6QRzcoXeOavU3sTrXQmMZRh5pu1Ga7xfaeFVlSLc55QwqkL1QQFor3ROQalWV+0lu3KLaAVlgdPGLnAs3F3MQcq1cZjM03r88j0nqYIiuWAPWaqKZNf21JkvPttO5Q1YrLeIkAwKm+BA9VzJ9DboDGUI7rAF0/86OQg9hEksUy1XF2xp15ZpQavUkOLltWuRocbxs3cZRWGtVBKRmqXF31VoQcr70E5Y1pJvJyBild1YxNzXxq5Ia9mViEzuQvZ875a2vMIE7ZYxwgetrkgHU5ACnkDKagtLARSos5ooRymSnNiGNRcloKQ6kziJOhMV1LckVESiQZUK+TN0xhsOVqeHo1vXjWOKEZSfOmnO2Z0lBXFTFfvbbAOFD7HXk8ZkjcmG3y07JaxRUZkZo7Ow9O2CkHSDwFVG01U6YIEeYtsztCTnvjc2tNlLiyOz5+NCLS5yWP5RKcwqZtptdU3qw1P7l5xzaX0x0rtijz5+Y6dd1ewQ8jIGxaJ395jkxV7N9mocxl7MmU9ouQwWYwxpz4y4NJcuUrvlmTZZP+qZcb7mRBaP1YZePx5pAOhH8bZ74IMX3ilpAEHzM1Ru6Yqx8vIqxGxcern6dRgHuIbGqRG5ByX1SOmbwg0quGk6HtY8rxxXlZsDWe0vA/vfEAS0LfxKBpwlaF8xtyH4MrRGQhXsMdALVVbmB9bSx6foPRmbkfl1cvv1OPsafFcPbOFGkB4MYCXLULBOWmK30CfbQg4P/UZIm8PzLxfLi5ymgLqZQlmwKhSjN/4dSlEnKHK170r9NyZevUANFDYykVWYK1aqStprCRkiuNjtE9H/x/LiGiDPKscZC5Ns3UwSYuElNPEM7BU4rgXIKa020MnzfbkU5kNDr2sP+SRjrDG1xN0PONRlDZkhQIHvbJmuaDDXfoKaWbAqVqTDPt3B7edXVUPvIY7UiLcmSad3kz27fCG073jyD+2/aFhS6XrK/LLaLDhpQTzS8yoZKxU9QHjonUCoevG2UqnqrNXWY7hSHh8X1kMj9b0pkp9tUizgkc7/ATnqCDnHHER5bXI8jCmhQYDlkQimV9d+/TkbXgRznPOWDpcPLem+XfbQneLKN8gbc6DCFkv2vvW1HF3dHqjNVSfviGdz5aDD6vWuH3LtPN5dfb+Dh7vry/gauv1w93N58vr+8X3z5PPk3AAD///Mamfg="
}
